### ISSUE TITLE
Possible python error

### ISSUE THREAD

**Issue by peterdfields** [ktrappe/daisy#6]
I get the following when running Daisy on the H. pylori dataset:

```
Start Joining Candidate Genomes
End Joining Candidate Genomes
Running sensitive mode
Start Yara Indexer
End Yara Indexer
Start Yara Mapping
End Yara Mapper
Start Converting Mapped Sam to BAM
End Converting Mapped Sam to BAM
Deleting Sam files
Start Sorting BAM
End Sorting BAM (qname)
Start Samtools Extract Unmapped to BAM
End Samtools Extract Unmapped to BAM
Start Samtools Sort Unmapped BAM
End Samtools Sort Unmapped BAM
Start Converting to Unmapped FASTQ
End Converting to Unmapped FASTQ
Start Swiss-Army-Knife (Sak) Mate 1
End Swiss-Army-Knife (Sak) Mate 1
Start Swiss-Army-Knife (Sak) Mate 2
End Swiss-Army-Knife (Sak) Mate 2
Start Gustaf Mate Joining
End Gustaf Mate Joining
Start STELLAR
End STELLAR
Traceback (most recent call last):
  File "../../daisy.py", line 852, in <module>
    pipeline(args)
  File "../../daisy.py", line 558, in pipeline
    '-gth', args.g_gth, '-ith', args.g_ith, '-ll', args.g_ll, '-le', args.g_le, '-cbp' if args.g_cbp is True else None, '-nth', args.g_nth] if x is not None]
AttributeError: 'Namespace' object has no attribute 'g_ll'
```

There doesn't seem to be anything obvious showing up in the log file to track down the error. I've also tried both python 2.7.9 and 3.4.0 and the error persists. I'm running Daisy on a Ubuntu 14.04 machine.

**Comment by ktrappe** [comment]
Thanks for the notification Peter! We are doing some refactoring at the moment and unfortunately I checked in a intermediate version where the parser is not synchronised. I will change this asap!

**Comment by peterdfields** [comment]
Thanks @ktrappe!

**Comment by ktrappe** [comment]
@peterdfields I fixed the parser error above, seems this was the only problem in this version.

**Comment by peterdfields** [comment]
Hi @ktrappe 

I pulled the update but the error hasn't changed much:

Traceback (most recent call last):
  File "../../daisy.py", line 852, in <module>
    pipeline(args)
  File "../../daisy.py", line 569, in pipeline
    '-gth', args.g_gth, '-ith', args.g_ith, '-ll', args.ll, '-le', args.le, '-cbp' if args.g_cbp is True else None, '-nth', args.g_nth] if x is not None]
AttributeError: 'Namespace' object has no attribute 'll'

I tried with both python 2.7.9 and 3.5.0. The following is version information for gustaf:

```
VERSION
    Last update: August 2014
    gustaf version: 1.0.0
    SeqAn version: 2.2.1
```

Is there a specfic version of python I should be using or other associated tools? Let me know if there is any additional info that might be helpful in tracking down the issue.

**Comment by ktrappe** [comment]
Sorry @peterdfields, this is not a python version problem but again a parser error from Gustaf (and also Yara). I only fixed the local namespace in the previous fix and not the global namespace call, my bad! I hope the current fix is now working for you.

**Comment by peterdfields** [comment]
That did the trick! thanks @ktrappe
